DROP TABLE IF EXISTS consulta CASCADE;
DROP TABLE IF EXISTS paciente CASCADE;
DROP TABLE IF EXISTS medico CASCADE;
DROP TABLE IF EXISTS tipo_consulta CASCADE;
DROP TABLE IF EXISTS plano_saude CASCADE;
DROP TABLE IF EXISTS local_atendimento CASCADE;